### ISSUE TITLE
Cant Connect 

### ISSUE THREAD

**Issue by Nfdk2024** [ChrisTerBeke/homey-uponor#10]
Hi
I cant Connect my Homey to the R208. I have uding a fixed adresse. But i fails. How Can I troubleshoot?

**Comment by ChrisTerBeke** [comment]
Hi,

Thanks for using the Homey Uponor app! Before debugging the app itself, can you confirm the following things for me?

* The Uponor Smatrix system is fully configured (room names etc.) and in the local (WiFi) network.
* You can reach the system using the Uponor app.
* Your Homey Pro lives in the same network (and same IP range, aka subnet) as your Uponor system.
* You can navigate to the IP address of your Uponor system in your browser and see a 403 Forbidden text.
* You have no firewalls, missing routes, or other known reasons that Homey cannot reach the Uponor system on the local network.

If the answer to all of these is "yes", we can figure out some steps to debug further.

Thanks!

Chris

**Comment by Nfdk2024** [comment]
Hi
I am using LAN not Wifi. 
but Can say yes to the rest

**Comment by ChrisTerBeke** [comment]
Hi,

Thanks for checking those things for me.

Can you tell me where it's going wrong? Are you not seeing any devices during the pairing flow? Or can you add the devices but are not getting any data?

Chris
